# Generated by Django 6.0.6 on 2026-07-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name_plural': 'food'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'food categories'},
        ),
    ]
