# Generated by Django 6.0.6 on 2026-07-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['full_name']},
        ),
    ]
