# Generated by Django 6.0.6 on 2026-07-12 15:36

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_cancelled_order_status_and_manual_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.customers.models.customer_avatar_upload_to),
        ),
    ]
