# Generated by Django 6.0.6 on 2026-07-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_site_header', models.CharField(default='Yummy Restaurant Admin', help_text='Header displayed on the Django admin site', max_length=255)),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
