# Generated by Django 6.0.6 on 2026-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_admin_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_received_message',
            field=models.TextField(default='Payment Verified Successfully. Your order for {{ items }} is now being prepared.', help_text='Available variables: {{ customer_name }}, {{ order_number }}, {{ items }}, {{ amount }}'),
        ),
    ]
