from django.db import models
from .constants import ORDER_STATUS_CHOICES, PAYMENT_STATUS_CHOICES, PAYMENT_METHOD_CHOICES, NOTIFICATION_TYPE_CHOICES


class OrderStatus(models.TextChoices):
    PENDING = ORDER_STATUS_CHOICES['PENDING'], 'Pending'
    PAYMENT_RECEIVED = ORDER_STATUS_CHOICES['PAYMENT_RECEIVED'], 'Payment Received'
    PREPARING = ORDER_STATUS_CHOICES['PREPARING'], 'Preparing'
    READY = ORDER_STATUS_CHOICES['READY'], 'Ready'
    DELIVERED = ORDER_STATUS_CHOICES['DELIVERED'], 'Delivered'
    CANCELLED = ORDER_STATUS_CHOICES['CANCELLED'], 'Cancelled'


class PaymentStatus(models.TextChoices):
    PENDING = PAYMENT_STATUS_CHOICES['PENDING'], 'Pending'
    APPROVED = PAYMENT_STATUS_CHOICES['APPROVED'], 'Approved'
    REJECTED = PAYMENT_STATUS_CHOICES['REJECTED'], 'Rejected'


class PaymentMethod(models.TextChoices):
    MOBILE_MONEY = PAYMENT_METHOD_CHOICES['MOBILE_MONEY'], 'Mobile Money'
    CARD = PAYMENT_METHOD_CHOICES['CARD'], 'Card'


class NotificationType(models.TextChoices):
    PAYMENT_RECEIVED = NOTIFICATION_TYPE_CHOICES['PAYMENT_RECEIVED'], 'Payment Received'
    PAYMENT_REJECTED = NOTIFICATION_TYPE_CHOICES['PAYMENT_REJECTED'], 'Payment Rejected'
    ORDER_CONFIRMED = NOTIFICATION_TYPE_CHOICES['ORDER_CONFIRMED'], 'Order Confirmed'
    ORDER_PREPARING = NOTIFICATION_TYPE_CHOICES['ORDER_PREPARING'], 'Order Preparing'
    ORDER_READY = NOTIFICATION_TYPE_CHOICES['ORDER_READY'], 'Order Ready'
    ORDER_DELIVERED = NOTIFICATION_TYPE_CHOICES['ORDER_DELIVERED'], 'Order Delivered'
    MANUAL = NOTIFICATION_TYPE_CHOICES['MANUAL'], 'Manual'
