# Generated by Django 6.0.6 on 2026-07-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customerprofile')),
            ],
        ),
    ]
