# Generated by Django 6.0.6 on 2026-07-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('manual', 'Manual')], max_length=50),
        ),
    ]
