# Generated by Django 6.0.6 on 2026-07-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_cancelled_order_status_and_manual_notification_type'),
        ('orders', '0002_add_cancelled_order_status_and_manual_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
